commandlinefu_id: 5899
translator:
  weibo: ''
hide: true
command: |-
  dhclient wlan0 && sbnt=$(ifconfig wlan0 |grep "inet addr" |cut -d ":" -f 2 | cut -d "." -f 1-3) && nmap $sbnt.0/24 -sP
summary: |-
  Autofind alive hosts on subnet upon connect
