commandlinefu_id: 9903
translator:
  weibo: ''
hide: true
command: |-
  for i in `netstat -rn|egrep -v "Interface|Routing"|awk '{print $5}'`;do ifconfig $i;done
summary: |-
  Equivalent to ifconfig -a in HPUX
