commandlinefu_id: 1214
translator:
  weibo: ''
hide: true
command: |-
  IPADDR=`ifconfig eth0 | grep -i inet | awk -F: '{print $2}'| awk '{print $1}'`
summary: |-
  Filtering IP address from ifconfig usefule in scripts
