commandlinefu_id: 2715
translator:
  weibo: ''
hide: true
command: |-
  /sbin/ifconfig eth0 | grep "inet addr" | sed -e 's/.*inet addr:\(.*\) B.*/\1/g'
summary: |-
  Read just the IP address of a device
